# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
theme: jekyll-theme-modernist # Gem-based Jekyll Themes

# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: dark # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: tomorrow-night # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : Xinyun Liu
description: > # this means to ignore newlines until "Language & timezone"
  Your Site Description


## => Language and Timezone
##############################
lang: en # the language of your site, default as "en"
timezone: US # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : # "person" (default), "organization"
  name      : Xinyun Liu
  url       :
  avatar    : # path or url of avatar image (square)
  bio       : I am an amazing person.
  email     : xl73@rice.edu
  facebook  : # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : https://www.linkedin.com/in/xinyun-leo-liu/ # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: zxqlxy/zxqlxy.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: # false (default), true

## Chart
chart: # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: false # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : # LeanCloud App id
    app_key     : # LeanCloud App key
    placeholder : # Prompt information
    visitor     : # false (default)
    meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: google # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : 136835643 # Google Analytics id for the site
    anonymize_ip: true # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji




#############################
# For Gallery


#############################
#        TO FILL            #
#############################

# The title that appears on the tab
gallery_title: Xinyun Liu's Gallery

# The title on the web page
full_name: Xinyun Liu

# The type of layout
# Options: ROWS, SQUARES, COLUMNS
layout_style: ROWS

# Variables below are default. Feel free to customize the values below, but do
# not remove the property.

# Integer: Spacing between each photo
spacing: 10

# Boolean(true|false): Shuffle the photos in the album
shuffle: true

# Integer: Number of columns for square or columns
columns: 4

# Integer: Max height for rows
max_height: 400

# Handle
instagram: zxqlxy1999
fivepx: liuxinyun6


######################
# END OF CONFIG CODE #
#  Ignore below :)   #
######################
#
# Name of your gallery (this will show up at the top of your page and in the RSS feed)
name: Gallery

# Short description (goes below the title; it will also be used in the RSS feed)
g_description: Photography Portfolio

# Your name, as you want it to appear underneath each post and in the footer
author_: Andy Zhang

# Your email if you want it to be linked on the contact page
author_email: andzhng@gmail.com

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
baseurl: /

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
# url: http://andyzhang.net/gallery

  
